/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from "vue";

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonGroup: typeof import('./src/components/SurveyComs/EditItems/ButtonGroup.vue')['default']
    Cascader: typeof import('./src/components/SurveyComs/Materials/AdvancedComs/Cascader.vue')['default']
    CascaderOptionNode: typeof import('./src/components/SurveyComs/EditItems/CascaderOptionNode.vue')['default']
    CascaderOptionsEditor: typeof import('./src/components/SurveyComs/EditItems/CascaderOptionsEditor.vue')['default']
    ColorEditor: typeof import('./src/components/SurveyComs/EditItems/ColorEditor.vue')['default']
    DateTime: typeof import('./src/components/SurveyComs/Materials/AdvancedComs/DateTime.vue')['default']
    DateTimeTypeEditor: typeof import('./src/components/SurveyComs/EditItems/DateTimeTypeEditor.vue')['default']
    DescEditor: typeof import('./src/components/SurveyComs/EditItems/DescEditor.vue')['default']
    EditPannel: typeof import('./src/components/SurveyComs/EditItems/EditPannel.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/Common/Header.vue')['default']
    HeaderNav: typeof import('./src/components/Common/header-nav.vue')['default']
    ItalicEditor: typeof import('./src/components/SurveyComs/EditItems/ItalicEditor.vue')['default']
    MaterialsHeader: typeof import('./src/components/SurveyComs/Common/MaterialsHeader.vue')['default']
    MatrixOptionsEditor: typeof import('./src/components/SurveyComs/EditItems/MatrixOptionsEditor.vue')['default']
    MatrixSingle: typeof import('./src/components/SurveyComs/Materials/MatrixComs/MatrixSingle.vue')['default']
    MultiPicSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/MultiPicSelect.vue')['default']
    MultiSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/MultiSelect.vue')['default']
    OptionsEditor: typeof import('./src/components/SurveyComs/EditItems/OptionsEditor.vue')['default']
    OptionSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/OptionSelect.vue')['default']
    PicItem: typeof import('./src/components/SurveyComs/Common/PicItem.vue')['default']
    PicOptionsEditor: typeof import('./src/components/SurveyComs/EditItems/PicOptionsEditor.vue')['default']
    PositionEditor: typeof import('./src/components/SurveyComs/EditItems/PositionEditor.vue')['default']
    RateScore: typeof import('./src/components/SurveyComs/Materials/AdvancedComs/RateScore.vue')['default']
    RateTextEditor: typeof import('./src/components/SurveyComs/EditItems/RateTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signature: typeof import('./src/components/SurveyComs/Materials/AdvancedComs/Signature.vue')['default']
    SignatureConfigEditor: typeof import('./src/components/SurveyComs/EditItems/SignatureConfigEditor.vue')['default']
    SinglePicSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/SinglePicSelect.vue')['default']
    SingleSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/SingleSelect.vue')['default']
    SizeEditor: typeof import('./src/components/SurveyComs/EditItems/SizeEditor.vue')['default']
    Slider: typeof import('./src/components/SurveyComs/Materials/AdvancedComs/Slider.vue')['default']
    SliderConfigEditor: typeof import('./src/components/SurveyComs/EditItems/SliderConfigEditor.vue')['default']
    SurveyComGroup: typeof import('./src/components/Editor/SurveyComGroup.vue')['default']
    SurveyComItem: typeof import('./src/components/Editor/SurveyComItem.vue')['default']
    SurveyPagination: typeof import('./src/components/Common/SurveyPagination.vue')['default']
    TextInput: typeof import('./src/components/SurveyComs/Materials/InputComs/TextInput.vue')['default']
    TextInputTypeEditor: typeof import('./src/components/SurveyComs/EditItems/TextInputTypeEditor.vue')['default']
    TextNote: typeof import('./src/components/SurveyComs/Materials/NoteComs/TextNote.vue')['default']
    TextTypeEditor: typeof import('./src/components/SurveyComs/EditItems/TextTypeEditor.vue')['default']
    TitleEditor: typeof import('./src/components/SurveyComs/EditItems/TitleEditor.vue')['default']
    Transfer: typeof import('./src/components/SurveyComs/Materials/AdvancedComs/Transfer.vue')['default']
    UserProfile: typeof import('./src/components/Common/UserProfile.vue')['default']
    WeightEditor: typeof import('./src/components/SurveyComs/EditItems/WeightEditor.vue')['default']
  }
}

// For TSX support
declare global {
  const ButtonGroup: (typeof import("./src/components/SurveyComs/EditItems/ButtonGroup.vue"))["default"];
  const Cascader: (typeof import("./src/components/SurveyComs/Materials/AdvancedComs/Cascader.vue"))["default"];
  const CascaderOptionNode: (typeof import("./src/components/SurveyComs/EditItems/CascaderOptionNode.vue"))["default"];
  const CascaderOptionsEditor: (typeof import("./src/components/SurveyComs/EditItems/CascaderOptionsEditor.vue"))["default"];
  const ColorEditor: (typeof import("./src/components/SurveyComs/EditItems/ColorEditor.vue"))["default"];
  const DateTime: (typeof import("./src/components/SurveyComs/Materials/AdvancedComs/DateTime.vue"))["default"];
  const DateTimeTypeEditor: (typeof import("./src/components/SurveyComs/EditItems/DateTimeTypeEditor.vue"))["default"];
  const DescEditor: (typeof import("./src/components/SurveyComs/EditItems/DescEditor.vue"))["default"];
  const EditPannel: (typeof import("./src/components/SurveyComs/EditItems/EditPannel.vue"))["default"];
  const ElAvatar: (typeof import("element-plus/es"))["ElAvatar"];
  const ElButton: (typeof import("element-plus/es"))["ElButton"];
  const ElButtonGroup: (typeof import("element-plus/es"))["ElButtonGroup"];
  const ElCarousel: (typeof import("element-plus/es"))["ElCarousel"];
  const ElCarouselItem: (typeof import("element-plus/es"))["ElCarouselItem"];
  const ElCascader: (typeof import("element-plus/es"))["ElCascader"];
  const ElCheckbox: (typeof import("element-plus/es"))["ElCheckbox"];
  const ElCheckboxGroup: (typeof import("element-plus/es"))["ElCheckboxGroup"];
  const ElColorPicker: (typeof import("element-plus/es"))["ElColorPicker"];
  const ElDatePicker: (typeof import("element-plus/es"))["ElDatePicker"];
  const ElDialog: (typeof import("element-plus/es"))["ElDialog"];
  const ElForm: (typeof import("element-plus/es"))["ElForm"];
  const ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
  const ElIcon: (typeof import("element-plus/es"))["ElIcon"];
  const ElImage: (typeof import("element-plus/es"))["ElImage"];
  const ElInput: (typeof import("element-plus/es"))["ElInput"];
  const ElInputNumber: (typeof import("element-plus/es"))["ElInputNumber"];
  const ElLink: (typeof import("element-plus/es"))["ElLink"];
  const ElOption: (typeof import("element-plus/es"))["ElOption"];
  const ElPagination: (typeof import("element-plus/es"))["ElPagination"];
  const ElPopover: (typeof import("element-plus/es"))["ElPopover"];
  const ElRadio: (typeof import("element-plus/es"))["ElRadio"];
  const ElRadioGroup: (typeof import("element-plus/es"))["ElRadioGroup"];
  const ElRate: (typeof import("element-plus/es"))["ElRate"];
  const ElSelect: (typeof import("element-plus/es"))["ElSelect"];
  const ElSlider: (typeof import("element-plus/es"))["ElSlider"];
  const ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
  const ElTable: (typeof import("element-plus/es"))["ElTable"];
  const ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
  const ElTag: (typeof import("element-plus/es"))["ElTag"];
  const ElText: (typeof import("element-plus/es"))["ElText"];
  const ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
  const ElTransfer: (typeof import("element-plus/es"))["ElTransfer"];
  const ElUpload: (typeof import("element-plus/es"))["ElUpload"];
  const Header: (typeof import("./src/components/Common/Header.vue"))["default"];
  const HeaderNav: (typeof import("./src/components/Common/header-nav.vue"))["default"];
  const ItalicEditor: (typeof import("./src/components/SurveyComs/EditItems/ItalicEditor.vue"))["default"];
  const MaterialsHeader: (typeof import("./src/components/SurveyComs/Common/MaterialsHeader.vue"))["default"];
  const MatrixOptionsEditor: (typeof import("./src/components/SurveyComs/EditItems/MatrixOptionsEditor.vue"))["default"];
  const MatrixSingle: (typeof import("./src/components/SurveyComs/Materials/MatrixComs/MatrixSingle.vue"))["default"];
  const MultiPicSelect: (typeof import("./src/components/SurveyComs/Materials/SelectComs/MultiPicSelect.vue"))["default"];
  const MultiSelect: (typeof import("./src/components/SurveyComs/Materials/SelectComs/MultiSelect.vue"))["default"];
  const OptionsEditor: (typeof import("./src/components/SurveyComs/EditItems/OptionsEditor.vue"))["default"];
  const OptionSelect: (typeof import("./src/components/SurveyComs/Materials/SelectComs/OptionSelect.vue"))["default"];
  const PicItem: (typeof import("./src/components/SurveyComs/Common/PicItem.vue"))["default"];
  const PicOptionsEditor: (typeof import("./src/components/SurveyComs/EditItems/PicOptionsEditor.vue"))["default"];
  const PositionEditor: (typeof import("./src/components/SurveyComs/EditItems/PositionEditor.vue"))["default"];
  const RateScore: (typeof import("./src/components/SurveyComs/Materials/AdvancedComs/RateScore.vue"))["default"];
  const RateTextEditor: (typeof import("./src/components/SurveyComs/EditItems/RateTextEditor.vue"))["default"];
  const RouterLink: (typeof import("vue-router"))["RouterLink"];
  const RouterView: (typeof import("vue-router"))["RouterView"];
  const Signature: (typeof import("./src/components/SurveyComs/Materials/AdvancedComs/Signature.vue"))["default"];
  const SignatureConfigEditor: (typeof import("./src/components/SurveyComs/EditItems/SignatureConfigEditor.vue"))["default"];
  const SinglePicSelect: (typeof import("./src/components/SurveyComs/Materials/SelectComs/SinglePicSelect.vue"))["default"];
  const SingleSelect: (typeof import("./src/components/SurveyComs/Materials/SelectComs/SingleSelect.vue"))["default"];
  const SizeEditor: (typeof import("./src/components/SurveyComs/EditItems/SizeEditor.vue"))["default"];
  const Slider: (typeof import("./src/components/SurveyComs/Materials/AdvancedComs/Slider.vue"))["default"];
  const SliderConfigEditor: (typeof import("./src/components/SurveyComs/EditItems/SliderConfigEditor.vue"))["default"];
  const SurveyComGroup: (typeof import("./src/components/Editor/SurveyComGroup.vue"))["default"];
  const SurveyComItem: (typeof import("./src/components/Editor/SurveyComItem.vue"))["default"];
  const SurveyPagination: (typeof import("./src/components/Common/SurveyPagination.vue"))["default"];
  const TextInput: (typeof import("./src/components/SurveyComs/Materials/InputComs/TextInput.vue"))["default"];
  const TextInputTypeEditor: (typeof import("./src/components/SurveyComs/EditItems/TextInputTypeEditor.vue"))["default"];
  const TextNote: (typeof import("./src/components/SurveyComs/Materials/NoteComs/TextNote.vue"))["default"];
  const TextTypeEditor: (typeof import("./src/components/SurveyComs/EditItems/TextTypeEditor.vue"))["default"];
  const TitleEditor: (typeof import("./src/components/SurveyComs/EditItems/TitleEditor.vue"))["default"];
  const Transfer: (typeof import("./src/components/SurveyComs/Materials/AdvancedComs/Transfer.vue"))["default"];
  const UserProfile: (typeof import("./src/components/Common/UserProfile.vue"))["default"];
  const WeightEditor: (typeof import("./src/components/SurveyComs/EditItems/WeightEditor.vue"))["default"];
}
